#### Plugins ########
plugin_config_file: '$(rospack find elevation_mapping_cupy)/config/setups/turtle_bot/plugin_config.yaml'

pointcloud_channel_fusions:
  none: 'none'
  # rgb: 'color'
  # default: 'average'

image_channel_fusions:
  rgb: 'color'
  default: 'exponential'
  feat_.*: 'exponential'

#### Subscribers ########
subscribers:
  color_cam: # for color camera
    topic_name: '/camera/rgb/image_raw'
    camera_info_topic_name: '/camera/depth/camera_info'
    data_type: image
  semantic_cam: # for semantic images
    topic_name: '/front_cam/semantic_image'
    camera_info_topic_name: '/front_cam/camera/depth/camera_info_resized'
    channel_info_topic_name: '/front_cam/channel_info'
    data_type: image
  # fixed_semantic_cam: # for semantic images
  #   topic_name: '/front_cam/semantic_image'
  #   camera_info_topic_name: '/front_cam/camera/depth/camera_info_resized'
  #   channels: ["test", "test2", "test3"]
  #   data_type: image
  front_cam_pointcloud:
    topic_name: '/camera/depth/points'
    data_type: pointcloud
  feat_front:
    topic_name: /elevation_mapping/feat_f
    camera_info_topic_name: "/camera/depth/camera_info"
    channels: [ 'feat_0','feat_1','feat_2','feat_3','feat_4','feat_5','feat_6','feat_7','feat_8','feat_9' ]
    data_type: image


#### Publishers ########
publishers:
  elevation_map_raw:
    layers: ['elevation', 'traversability', 'variance','rgb','sem_fil', 'person', 'chair', 'sofa']
    basic_layers: ['elevation']
    fps: 5.0
  elevation_map_filter:
    layers: ['min_filter', 'smooth', 'inpaint', 'elevation','rgb','sem_fil']
    basic_layers: ['min_filter']
    fps: 3.0