#### Plugins ########
plugin_config_file: '$(rospack find elevation_mapping_cupy)/config/setups/turtle_bot/plugin_config.yaml'

#### Subscribers ########
subscribers:
  front_cam:
    channels: ['rgb', 'grass','tree',"person" ]
    fusion: [ 'color','class_average','class_average','class_average' ]
    topic_name: '/elevation_mapping/pointcloud_semantic'
    semantic_segmentation: True
    publish_segmentation_image: True
    segmentation_model: 'lraspp_mobilenet_v3_large' # detectron_coco_panoptic_fpn_R_101_3x, lraspp_mobilenet_v3_large
    show_label_legend: False
    data_type: pointcloud

    cam_info_topic: "/camera/depth/camera_info"
    image_topic: "/camera/rgb/image_raw"
    depth_topic: "/camera/depth/image_raw"
    cam_frame: "camera_rgb_optical_frame"


#### Publishers ########
publishers:
  elevation_map_raw:
    layers: ['elevation', 'traversability', 'variance','rgb','sem_fil']
    basic_layers: ['elevation']
    fps: 5.0
  elevation_map_filter:
    layers: ['min_filter', 'smooth', 'inpaint', 'elevation','rgb','sem_fil']
    basic_layers: ['min_filter']
    fps: 3.0