#### Subscribers ########
subscribers:
  sem_front:
    fusion: [ "class_average","class_average","class_average","class_average","class_average","class_average" ]
    image_topic: "/alphasense_driver_ros/cam4/debayered"
    semantic_segmentation: True
    sem_seg_topic: "/elevation_mapping/semantic_seg_f"
    sem_seg_image_topic: "/elevation_mapping/semantic_seg_im_f"
    segmentation_model: "detectron_coco_panoptic_fpn_R_101_3x"
    show_label_legend: False
    channels: [ 'grass','dirt','tree','sky','road','sand' ]
    image_info_topic: "/alphasense_driver_ros/cam4/camera_info"
    resize: 0.25

  sem_right:
    fusion: [ "class_average","class_average","class_average","class_average" ,"class_average","class_average" ]
    image_topic: "/alphasense_driver_ros/cam5/debayered"
    semantic_segmentation: True
    sem_seg_topic: "/elevation_mapping/semantic_seg_r"
    sem_seg_image_topic: "/elevation_mapping/semantic_seg_im_r"
    segmentation_model: "detectron_coco_panoptic_fpn_R_101_3x"
    show_label_legend: False
    channels: [ 'grass','dirt','tree','sky','road','sand' ]
    image_info_topic: "/alphasense_driver_ros/cam5/camera_info"
    resize: 0.5

  sem_left:
    fusion: [ "class_average","class_average","class_average","class_average","class_average","class_average" ]
    image_topic: "/alphasense_driver_ros/cam3/debayered"
    semantic_segmentation: True
    sem_seg_topic: "/elevation_mapping/semantic_seg_l"
    sem_seg_image_topic: "/elevation_mapping/semantic_seg_im_l"
    segmentation_model: "detectron_coco_panoptic_fpn_R_101_3x"
    show_label_legend: False
    channels: [ 'grass','dirt','tree','sky','road','sand' ]
    image_info_topic: "/alphasense_driver_ros/cam3/camera_info"
    resize: 0.5

#  sem_depth_front:
#    fusion: [ "class_average","class_average","class_average","class_average","class_average","class_average" ]
#    image_topic: "/depth_camera_front/color/image_raw"
#    semantic_segmentation: True
#    sem_seg_topic: "/elevation_mapping/depth_semantic_seg_f"
#    sem_seg_image_topic: "/elevation_mapping/depth_semantic_seg_im_f"
#    segmentation_model: "detectron_coco_panoptic_fpn_R_101_3x"
#    show_label_legend: False
#    channels: [ 'grass','dirt','tree','sky','road','sand' ]
#    image_info_topic: "/depth_camera_front/color/camera_info"
#    resize: 0.5
#
#  sem_depth_left:
#    fusion: [ "class_average","class_average","class_average","class_average","class_average","class_average" ]
#    image_topic: "/depth_camera_left/color/image_raw/compressed"
#    semantic_segmentation: True
#    sem_seg_topic: "/elevation_mapping/depth_semantic_seg_r"
#    sem_seg_image_topic: "/elevation_mapping/depth_semantic_seg_im_r"
#    segmentation_model: "detectron_coco_panoptic_fpn_R_101_3x"
#    show_label_legend: False
#    channels: [ 'grass','dirt','tree','sky','road','sand' ]
#    image_info_topic: "/depth_camera_left/color/camera_info"
#    resize: 0.5
#
#  sem_depth_right:
#    fusion: [ "class_average","class_average","class_average","class_average","class_average","class_average" ]
#    image_topic: "/depth_camera_right/color/image_raw/compressed"
#    semantic_segmentation: True
#    sem_seg_topic: "/elevation_mapping/depth_semantic_seg_r"
#    sem_seg_image_topic: "/elevation_mapping/depth_semantic_seg_im_r"
#    segmentation_model: "detectron_coco_panoptic_fpn_R_101_3x"
#    show_label_legend: False
#    channels: [ 'grass','dirt','tree','sky','road','sand' ]
#    image_info_topic: "/depth_camera_right/color/camera_info"
#    resize: 0.5

#  sem_wide_front:
#    fusion: [ "class_average","class_average","class_average","class_average","class_average","class_average" ]
#    image_topic: "/depth_camera_right/color/image_raw/compressed"
#    semantic_segmentation: True
#    sem_seg_topic: "/elevation_mapping/semantic_wide_seg_f"
#    sem_seg_image_topic: "/elevation_mapping/depth_semantic_seg_im_r"
#    segmentation_model: "detectron_coco_panoptic_fpn_R_101_3x"
#    show_label_legend: False
#    channels: [ 'grass','dirt','tree','sky','road','sand' ]
#    image_info_topic: "/depth_camera_right/color/camera_info"
#    resize: 0.5
#
#  sem_wide_back:
#    fusion: [ "class_average","class_average","class_average","class_average","class_average","class_average" ]
#    image_topic: "/depth_camera_right/color/image_raw/compressed"
#    semantic_segmentation: True
#    sem_seg_topic: "/elevation_mapping/semantic_wide_seg_b"
#    sem_seg_image_topic: "/elevation_mapping/depth_semantic_seg_im_r"
#    segmentation_model: "detectron_coco_panoptic_fpn_R_101_3x"
#    show_label_legend: False
#    channels: [ 'grass','dirt','tree','sky','road','sand' ]
#    image_info_topic: "/depth_camera_right/color/camera_info"
#    resize: 0.5

#  sem_back:
#    fusion: [ "class_average","class_average","class_average","class_average","class_average","class_average"  ]
#    image_topic: "/alphasense_driver_ros/cam6/debayered/compressed"
#    semantic_segmentation: True
#    sem_seg_topic: "/elevation_mapping/semantic_seg_b"
#    sem_seg_image_topic: "/elevation_mapping/semantic_seg_im_b"
#    segmentation_model: "detectron_coco_panoptic_fpn_R_101_3x"
#    show_label_legend: False
#    channels: ["grass","road",'tree','sky','sand','dirt']
#    image_info_topic: "/alphasense_driver_ros/cam6/camera_info"
#    resize: 1.0


