#### Subscribers ########
subscribers:
  #  alphasense_front_rgb:
  #    fusion: ['image_color']
  #    topic_name_camera: /alphasense_driver_ros/cam4/debayered/compressed
  #    topic_name_camera_info: /alphasense_driver_ros/cam4/camera_info
  #    channels: ["rgb_image"]
  #    data_type: image
  #
  #  alphasense_left_rgb:
  #    fusion: ['image_color']
  #    topic_name_camera: /alphasense_driver_ros/cam3/debayered/compressed
  #    topic_name_camera_info: /alphasense_driver_ros/cam3/camera_info
  #    channels: ["rgb_image"]
  #    data_type: image
  #
  #  alphasense_right_rgb:
  #    fusion: ['image_color']
  #    topic_name_camera: /alphasense_driver_ros/cam5/debayered/compressed
  #    topic_name_camera_info: /alphasense_driver_ros/cam5/camera_info
  #    channels: ["rgb_image"]
  #    data_type: image

  #  color_depth_front:
  #    fusion: ['exponential','exponential','exponential','exponential','exponential','exponential']
  #    topic_name_camera: /elevation_mapping/depth_semantic_seg_f
  #    topic_name_camera_info: /depth_camera_front/color/camera_info_resized
  #    channels: [ 'dirt', 'grass','tree','sky','road','sand' ]
  #    data_type: image
  #
  #  color_depth_left:
  #    fusion: ['exponential','exponential','exponential','exponential','exponential','exponential']
  #    topic_name_camera: /elevation_mapping/depth_semantic_seg_l
  #    topic_name_camera_info: /depth_camera_left/color/camera_info_resized
  #    channels: [ 'dirt', 'grass','tree','sky','road','sand' ]
  #    data_type: image
  #
  #  color_depth_right:
  #    fusion: ['exponential','exponential','exponential','exponential','exponential','exponential']
  #    topic_name_camera: /elevation_mapping/depth_semantic_seg_r
  #    topic_name_camera_info: /depth_camera_right/color/camera_info_resized
  #    channels: [ 'dirt', 'grass','tree','sky','road','sand' ]
  #    data_type: image

  wide_sem_front:
    fusion: [ 'exponential','exponential','exponential','exponential','exponential','exponential' ]
    topic_name_camera: /elevation_mapping/semantic_wide_seg_f
    topic_name_camera_info: /alphasense_driver_ros/cam4/camera_info_resized
    channels: [ 'grass','dirt','tree','sky','road','sand' ]
    data_type: image

  wide_sem_back:
    fusion: [ 'exponential','exponential','exponential','exponential','exponential','exponential' ]
    topic_name_camera: /elevation_mapping/semantic_wide_seg_b
    topic_name_camera_info: /alphasense_driver_ros/cam4/camera_info_resized
    channels: [ 'grass','dirt','tree','sky','road','sand' ]
    data_type: image

  sem_pred_front:
    fusion: [ 'exponential','exponential','exponential','exponential','exponential','exponential' ]
    topic_name_camera: /elevation_mapping/semantic_seg_f
    topic_name_camera_info: /alphasense_driver_ros/cam4/camera_info_resized
    channels: [ 'grass','dirt','tree','sky','road','sand' ]
    data_type: image

  sem_pred_right:
    fusion: [ 'exponential','exponential','exponential','exponential','exponential','exponential' ]
    topic_name_camera: /elevation_mapping/semantic_seg_r
    topic_name_camera_info: /alphasense_driver_ros/cam3/camera_info_resized
    channels: [ 'grass','dirt','tree','sky','road','sand' ]
    data_type: image

  sem_pred_left:
    fusion: [ 'exponential','exponential','exponential','exponential','exponential','exponential' ]
    topic_name_camera: /elevation_mapping/semantic_seg_l
    topic_name_camera_info: /alphasense_driver_ros/cam5/camera_info_resized
    channels: [ 'grass','dirt','tree','sky','road','sand' ]
    data_type: image



  #  sem_pred_left:
  #    fusion: ['exponential','exponential','exponential','exponential','exponential','exponential']
  #    topic_name_camera: /elevation_mapping/semantic_seg_b
  #    topic_name_camera_info: /alphasense_driver_ros/cam6/camera_info
  #    channels: ["grass","road",'tree','sky','sand','dirt']
  #    data_type: image

  front_bpearl:
    channels: []
    fusion: []
    topic_name: /robot_self_filter/bpearl_front/point_cloud
    data_type: pointcloud

  rear_bpearl:
    channels: []
    fusion: []
    topic_name: /robot_self_filter/bpearl_rear/point_cloud
    data_type: pointcloud
  #
  front_depth:
    channels: [ ]
    fusion: [ ]
    topic_name: /depth_camera_front/point_cloud_self_filtered
    data_type: pointcloud
  #
  #  rear_depth:
  #    channels: []
  #    fusion: []
  #    topic_name: /depth_camera_rear/point_cloud_self_filtered
  #    data_type: pointcloud

  left_depth:
    channels: [ ]
    fusion: [ ]
    topic_name: /depth_camera_left/point_cloud_self_filtered
    data_type: pointcloud

  right_depth:
    channels: [ ]
    fusion: [ ]
    topic_name: /depth_camera_right/point_cloud_self_filtered
    data_type: pointcloud

#  velodyne:
#    channels: []
#    fusion: []
#    topic_name: /point_cloud_filter/lidar/point_cloud_filtered
#    data_type: pointcloud

#  vel_nofil:
#    channels: [ ]
#    fusion: [ ]
#    topic_name: /lidar/point_cloud
#    data_type: pointcloud
