#### Subscribers ########
subscribers:

  feat_front:
    fusion: ['average','average','average','average','average','average','average','average','average','average']
    image_topic: "/camera/rgb/image_raw"
    image_info_topic: "/camera/depth/camera_info"
    semantic_segmentation: False
    feature_extractor: True
    feature_topic: "/elevation_mapping/feat_f"
    feat_image_topic: "/elevation_mapping/feat_im_f"
    show_label_legend: True
    channels: [ 'feat_0','feat_1','feat_2','feat_3','feat_4','feat_5','feat_6','feat_7','feat_8','feat_9' ]
    resize: 0.5
    input_size: [160,320]

#  sem_wide_back:
#    fusion: ['average','average','average','average','average','average','average','average','average','average']
#    image_topic: "/wide_angle_camera_rear/image_color_rect/compressed"
#    semantic_segmentation: False
#    feature_extractor: True
#    feature_topic: "/elevation_mapping/feat_b"
#    feat_image_topic: "/elevation_mapping/feat_im_b"
#    show_label_legend: False
#    channels: [ 'feat_0','feat_1','feat_2','feat_3','feat_4','feat_5','feat_6','feat_7','feat_8','feat_9' ]
#    image_info_topic: "/wide_angle_camera_rear/camera_info"
#    resize: 0.5
#    input_size: [160,320]




