subscribers:
#  sensor_name:
#    channels: ['feat_0','feat_1']
#    fusion: ['average','average']
#    topic_name: '/elevation_mapping/pointcloud_semantic'
  front_cam:
    channels: ['rgb','feat_0','feat_1','c_prob_0']
    fusion: ['color','average','average','class_average']
    topic_name: '/elvation_mapping/pointcloud_semantic'

