subscribers:
  sensor_name:
     channels: ['feat_0','feat_1']
     fusion: ['average','average']
     topic_name: '/elevation_mapping/pointcloud_semantic'

  front_cam:
    channels: ['rgb','feat_0','feat_1','grass','tree','fence','person']
    fusion: ['color','average','average','class_average','class_average','class_average','class_average']
    topic_name: '/elvation_mapping/pointcloud_semantic'
    semantic_segmentation: False
    segmentation_model: 'detectron_coco_panoptic_fpn_R_101_3x'
    feature_config:
      name: 'DINO'
      interpolation: 'bilinear'
      model: "vit_small"
      patch_size:  16
      dim: 5
      dropout: False
      dino_feat_type: "feat"
      input_size: [80, 160]
      projection_type: "nonlinear"

    cam_info_topic: "/camera/depth/camera_info"
    image_topic: "/camera/rgb/image_raw"
    depth_topic: "/camera/depth/image_raw"
    cam_frame: camera_rgb_optical_frame
    confidence: False
    confidence_topic: "/camera/depth/image_raw"
    confidence_threshold: 10
    feature_extractor: False
    
  front_bpearl:
    channels: []
    fusion: ['average']
    topic_name: /robot_self_filter/bpearl_front/point_cloud
  
  rear_bpearl:
    channels: []
    fusion: ['average']
    topic_name: /robot_self_filter/bpearl_rear/point_cloud

  front_depth:
    channels: []
    fusion: ['average']
    topic_name: /depth_camera_front/point_cloud_self_filtered
  
  rear_depth:
    channels: []
    fusion: ['average']
    topic_name: /depth_camera_rear/point_cloud_self_filtered
  
  left_depth:
    channels: []
    fusion: ['average']
    topic_name: /depth_camera_left/point_cloud_self_filtered
  
  right_depth:
    channels: []
    fusion: ['average']
    topic_name: /depth_camera_right/point_cloud_self_filtered