#### Subscribers ########
subscribers:
  front_cam:
    channels: [ 'rgb']
    fusion: [ 'color']
    topic_name: '/elvation_mapping/pointcloud_semantic'
    semantic_segmentation: False
    segmentation_model: 'lraspp_mobilenet_v3_large'
    show_label_legend: False
    data_type: pointcloud
    cam_info_topic: "/zed2i/zed_node/depth/camera_info"
    image_topic: "/zed2i/zed_node/left/image_rect_color"
    depth_topic: "/zed2i/zed_node/depth/depth_registered"
    cam_frame: "zed2i_right_camera_optical_frame"
    confidence: True
    confidence_topic: "/zed2i/zed_node/confidence/confidence_map"
    confidence_threshold: 10
    feature_extractor: False