subscribers:
#  sensor_name: #if you have multiple sensors assign different names
#    channels: ['features','person'] # names of the channels, for sem seg it should be the same name as the
                                    # pretrained network uses
#    fusion: ['average','class_average'] # the fusion algorithm type used.
                                    # Pick between: ['color', 'average','class_average']
#    topic_name: '/elevation_mapping/pointcloud_semantic' # of the published pointcloud subscribed by the el_map
  front_cam:
    channels: ['rgb','feat_0','feat_1','grass','tree','fence','person']
    fusion: ['color','average','average','class_average','class_average','class_average','class_average']
    topic_name: '/elvation_mapping/pointcloud_semantic'
    semantic_segmentation: False
    segmentation_model: 'detectron_coco_panoptic_fpn_R_101_3x'
    feature_config:
      name: 'DINO'
      interpolation: 'bilinear'
      model: "vit_small"
      patch_size:  16
      dim: 5
      dropout: False
      dino_feat_type: "feat"
      input_size: [80, 160]
      projection_type: "nonlinear"

    cam_info_topic: "/camera/depth/camera_info"
    image_topic: "/camera/rgb/image_raw"
    depth_topic: "/camera/depth/image_raw"
    cam_frame: camera_rgb_optical_frame
    confidence: False
    confidence_topic: "/camera/depth/image_raw"
    confidence_threshold: 10
    feature_extractor: False




