subscribers:
#  sensor_name:
#    channels: ['feat_0','feat_1']
#    fusion: ['average','average']
#    topic_name: '/elevation_mapping/pointcloud_semantic'
  front_cam:
    channels: ['rgb' ]
    fusion: [ 'color']
    topic_name: '/elevation_mapping/pointcloud_semantic'
    data_type: pointcloud

    cam_info_topic: "/camera/depth/camera_info"
    image_topic: "/camera/rgb/image_raw"
    depth_topic: "/camera/depth/image_raw"
    cam_frame: "camera_rgb_optical_frame"
