plugin_config_file: '$(rospack find elevation_mapping_cupy)/config/setups/anymal/anymal_plugin_config.yaml'

#### Publishers ########
# topic_name:
#   layers:               # Choose from 'elevation', 'variance', 'traversability', 'time', 'normal_x', 'normal_y', 'normal_z', 'color', plugin_layer_names
#   basic_layers:         # basic_layers for valid cell computation (e.g. Rviz): Choose a subset of `layers`.
#   fps:                  # Publish rate. Use smaller value than `map_acquire_fps`.

publishers:
  elevation_map_raw:
    layers: ['elevation', 'traversability', 'variance']
    basic_layers: ['elevation', 'traversability']
    fps: 5.0

  semantic_map_raw:
    layers: ['elevation', 'traversability']
    basic_layers: ['elevation', 'traversability']
    fps: 5.0

#### Subscribers ########
subscribers:
  front_upper_depth:
    channels: []
    fusion: []
    topic_name: /depth_camera_front_upper/point_cloud_self_filtered
    data_type: pointcloud

  front_lower_depth:
    channels: []
    fusion: []
    topic_name: /depth_camera_front_lower/point_cloud_self_filtered
    data_type: pointcloud

  rear_upper_depth:
    channels: []
    fusion: []
    topic_name: /depth_camera_rear_upper/point_cloud_self_filtered
    data_type: pointcloud

  rear_lower_depth:
    channels: []
    fusion: []
    topic_name: /depth_camera_rear_lower/point_cloud_self_filtered
    data_type: pointcloud

  left_depth:
    channels: []
    fusion: []
    topic_name: /depth_camera_left/point_cloud_self_filtered
    data_type: pointcloud

  right_depth:
    channels: []
    fusion: []
    topic_name: /depth_camera_right/point_cloud_self_filtered
    data_type: pointcloud

  # velodyne:
  #   channels: []
  #   fusion: []
  #   topic_name: /point_cloud_filter/lidar/point_cloud_filtered
  #   data_type: pointcloud

  front_bpearl:
    channels: []
    fusion: []
    topic_name: /robot_self_filter/bpearl_front/point_cloud
    data_type: pointcloud

  rear_bpearl:
    channels: []
    fusion: []
    topic_name: /robot_self_filter/bpearl_rear/point_cloud
    data_type: pointcloud