#### Subscribers ########
subscribers:
  front_cam:
    channels: ['grass','tree',"person" ]
    fusion: ['class_average','class_average','class_average'  ]
    semantic_segmentation: True
    segmentation_model: 'detectron_coco_panoptic_fpn_R_101_3x' # detectron_coco_panoptic_fpn_R_101_3x, lraspp_mobilenet_v3_large
    show_label_legend: False
    image_topic: "/camera/rgb/image_raw"
    image_info_topic: "/camera/depth/camera_info"
    resize: 0.5

    sem_seg_topic: "/elevation_mapping/semantic_front"
    sem_seg_image_topic: "/elevation_mapping/semantic_image_front"